server:
  port: 18082
spring:
  application:
    name: file
  servlet:
    multipart:
      #max-file-size是单个文件大小，max-request-size是设置请求的数据大小（包括文件和form表单等）
      max-file-size: 10MB
      max-request-size: 10MB
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:18080/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true